# Generated by Django 2.1.1 on 2018-11-07 13:09

import app.my_storage
import app.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('slider', '0002_auto_20181102_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('become_partner', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Стать партнёром')),
                ('content_bottom', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Нижний контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей')),
                ('cases', models.ManyToManyField(blank=True, related_name='cases', to='catalog.Make', verbose_name='Всегда есть чехлы для')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slider.Slider', verbose_name='Слайдер (Наша фабрика)')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Контакты / Команда / Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Depd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Помощь',
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_items', to='page.Help')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Описание над заголовком')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('header_slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slider.Slider', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Иконка')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_items', to='page.Home', verbose_name='Родительская')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('icon', models.TextField(blank=True, verbose_name='SVG Иконка')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='page.Home', verbose_name='Родительская')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Как мы работаем',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('content_bottom', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент внизу страницы')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
            },
        ),
        migrations.CreateModel(
            name='OurOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото (510x287)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('url', models.CharField(help_text='Если сылка на текущий сайт, то URL должен выглядеть так: <code>/path/to/</code>', max_length=255, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='page.About')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('PARTNERS', 'Наши партнёры в России'), ('OTHER_PARTNERS', 'Наши партнёры в других странах'), ('INSTALL', 'Где можно установить')], max_length=255, verbose_name='Раздел')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('tab_title', models.CharField(max_length=255, verbose_name='Заголовок таба')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация')),
                ('map', models.TextField(blank=True, verbose_name='Карта')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='page.Contact', verbose_name='Родительская')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории портфолио',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('contact_form', models.BooleanField(default=False, verbose_name='Контактная форма')),
                ('title', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото (510x595)')),
                ('video', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Depd', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_items', to='page.Info', verbose_name='Инфо')),
            ],
            options={
                'verbose_name': 'Таб',
                'verbose_name_plural': 'Инфо-табы',
            },
        ),
        migrations.CreateModel(
            name='TabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_section_items', to='page.TabItem')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('video', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение (800x450)')),
                ('caption', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.PortfolioCategory', verbose_name='Категория')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.StaffMember', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
