# Generated by Django 2.1.1 on 2018-12-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Контакты, Команда, Отзывы'},
        ),
    ]
