# Generated by Django 2.1.1 on 2019-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20181207_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='script',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='JavaScript'),
        ),
    ]
