# Generated by Django 2.1.1 on 2019-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_info_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='script',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='JavaScript'),
        ),
    ]
