# Generated by Django 2.1.1 on 2019-03-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20190326_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='script',
        ),
    ]
