# Generated by Django 2.1.1 on 2020-02-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20200204_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='help',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='info',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
    ]
