# Generated by Django 2.1.1 on 2020-02-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20200205_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='meta_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='home',
            name='seo_title',
        ),
    ]
