# Generated by Django 2.1.1 on 2018-11-21 10:55

import app.my_storage
import app.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Аккордион',
            },
        ),
        migrations.CreateModel(
            name='Pane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Панели',
            },
        ),
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='vacations', unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('content_middle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент в середине')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AddField(
            model_name='pane',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacations'),
        ),
        migrations.AddField(
            model_name='accordion',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacations'),
        ),
    ]
