# Generated by Django 2.1.1 on 2019-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20181121_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='work_time_header',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы в шапке'),
        ),
    ]
