# Generated by Django 2.1.1 on 2019-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_promocode'),
        ('settings', '0005_general_work_time_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='common_accessories', to='catalog.UniversalProduct', verbose_name='Аксессуары'),
        ),
    ]
