# Generated by Django 2.1.1 on 2020-02-04 03:01

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_general_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='', verbose_name='Изображение для соц.сетей'),
        ),
    ]
