# Generated by Django 2.1.1 on 2020-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_blogwidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwidget',
            name='url',
            field=models.CharField(help_text='URL will be opened in a new tab but URI in the same tab.', max_length=255, verbose_name='Ссылка'),
        ),
    ]
