# Generated by Django 2.1.1 on 2020-02-04 03:01

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20181102_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
