# Generated by Django 2.1.1 on 2018-11-30 17:02

import app.my_storage
import app.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Аккордион',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('widget_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок виджета')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение (500x296)')),
                ('video', models.URLField(blank=True, help_text='Выводится кнопкой при наведении на миниатюру.', verbose_name='Ссылка на видео')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('discounted', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание акции')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение для соц. сетей')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='PromotionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='promotion', max_length=255, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='СЕО Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ключевые слова')),
                ('meta_image', models.ImageField(blank=True, null=True, storage=app.my_storage.MyStorage(), upload_to=app.utils.fn, verbose_name='Изображение для соц. сетей')),
            ],
            options={
                'verbose_name': 'Каталог акций',
                'verbose_name_plural': 'Каталог акций',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('video', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение (1110x390)')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='promotion.Promotion')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.AddField(
            model_name='accordion',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_items', to='promotion.Promotion'),
        ),
    ]
