# Generated by Django 2.1.1 on 2018-12-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='install_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за установку'),
        ),
        migrations.AlterField(
            model_name='universalcategory',
            name='products_type',
            field=models.CharField(choices=[('ACCESSORY', 'Аксессуары'), ('MATE', 'Автоковрики'), ('CAPE', 'Автонакидки'), ('BRAID', 'Оплётки')], max_length=20, verbose_name='Тип товаров'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='product_type',
            field=models.CharField(choices=[('ACCESSORY', 'Аксессуары'), ('MATE', 'Автоковрики'), ('CAPE', 'Автонакидки'), ('BRAID', 'Оплётки')], default='DRAFT', max_length=20, verbose_name='Тип товара'),
        ),
    ]
