# Generated by Django 2.1.1 on 2018-12-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181208_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='code',
        ),
    ]
