# Generated by Django 2.1.1 on 2018-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181212_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Часть артикула'),
        ),
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Часть артикула'),
        ),
    ]
