# Generated by Django 2.1.1 on 2019-01-16 13:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181226_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопрос - Ответ',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('video', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='catalog.UniversalProduct', verbose_name='Аксессуары'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Кузов (180x110)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='catalogpage',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='color',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью (386x386)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Миниатюра (30x40)'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='make',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение (500x296)'),
        ),
        migrations.AlterField(
            model_name='make',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='universalcolor',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью (386x386)'),
        ),
        migrations.AlterField(
            model_name='universalcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Миниатюра (50x65)'),
        ),
        migrations.AlterField(
            model_name='universalimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение (800x450)'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AddField(
            model_name='case',
            name='qna',
            field=models.ManyToManyField(blank=True, to='catalog.QnA', verbose_name='Вопрос - Ответ'),
        ),
        migrations.AddField(
            model_name='case',
            name='tab_reviews',
            field=models.ManyToManyField(blank=True, to='catalog.Reviews', verbose_name='Обзоры'),
        ),
    ]
