# Generated by Django 2.1.1 on 2019-01-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_reviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalproduct',
            name='qna',
            field=models.ManyToManyField(blank=True, to='catalog.QnA', verbose_name='Вопрос - Ответ'),
        ),
        migrations.AddField(
            model_name='universalproduct',
            name='tab_reviews',
            field=models.ManyToManyField(blank=True, to='catalog.Reviews', verbose_name='Обзоры'),
        ),
    ]
