# Generated by Django 2.1.1 on 2019-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190125_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес товара (кг)'),
        ),
        migrations.AddField(
            model_name='universalproduct',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес товара (кг)'),
        ),
    ]
