# Generated by Django 2.1.1 on 2019-02-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190201_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalproduct',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='_universalproduct_accessories_+', to='catalog.UniversalProduct', verbose_name='Аксессуары'),
        ),
        migrations.AddField(
            model_name='universalproduct',
            name='install',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Install', verbose_name='Установка'),
        ),
    ]
