# Generated by Django 2.1.1 on 2019-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190218_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='universalcolor',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
