# Generated by Django 2.1.1 on 2019-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190311_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universalcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterField(
            model_name='color',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью (386x386)'),
        ),
        migrations.AlterField(
            model_name='universalcolor',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью (386x386)'),
        ),
    ]
