# Generated by Django 2.1.1 on 2019-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_color_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['order'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterField(
            model_name='color',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
