# Generated by Django 2.1.1 on 2019-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190522_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
