# Generated by Django 2.1.1 on 2019-07-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190522_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalproduct',
            name='product_type',
            field=models.CharField(choices=[('ACCESSORY', 'Аксессуары'), ('MATE', 'Автоковрики'), ('CAPE', 'Автонакидки'), ('BRAID', 'Оплётки')], default='ACCESSORY', max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLIC', 'Опубликованно')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
    ]
