# Generated by Django 2.1.1 on 2019-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20191211_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalcategory',
            name='slug',
            field=models.SlugField(default='test', max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
