# Generated by Django 2.1.1 on 2020-02-04 03:01

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20191211_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['order'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Кузов (180x110)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='catalogpage',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='color',
            name='big_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Превью (386x386)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Миниатюра (30x40)'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='make',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение (500x296)'),
        ),
        migrations.AlterField(
            model_name='make',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='universalcategory',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение (800x450)'),
        ),
        migrations.AlterField(
            model_name='universalcolor',
            name='big_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Превью (386x386)'),
        ),
        migrations.AlterField(
            model_name='universalcolor',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Миниатюра (50x65)'),
        ),
        migrations.AlterField(
            model_name='universalimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение (800x450)'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
    ]
