# Generated by Django 2.1.1 on 2020-02-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200204_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='catalogpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='make',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='universalproduct',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Мета описание'),
        ),
    ]
