# Generated by Django 2.1.1 on 2020-02-04 03:43

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200204_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=260, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='universalcategory',
            name='meta_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для соц. сетей'),
        ),
        migrations.AddField(
            model_name='universalcategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='universalcategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='СЕО Заголовок'),
        ),
    ]
