# Generated by Django 2.1.1 on 2020-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200204_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['order'], 'verbose_name': 'Чехол', 'verbose_name_plural': 'Чехлы'},
        ),
        migrations.AlterField(
            model_name='case',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
