# Generated by Django 2.1.1 on 2020-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200306_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['my_order'], 'verbose_name': 'Чехол', 'verbose_name_plural': 'Чехлы'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='order',
        ),
        migrations.AddField(
            model_name='case',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
