# Generated by Django 2.1.1 on 2020-03-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200306_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Чехол', 'verbose_name_plural': 'Чехлы'},
        ),
    ]
