# Generated by Django 2.1.1 on 2019-06-27 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('hex', models.CharField(help_text='Пример: #a4a4a4', max_length=7, verbose_name='Цвет')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default='0', verbose_name='Цена')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Основа',
                'verbose_name_plural': 'Основы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='case-builder', editable=False, unique=True)),
                ('title', models.CharField(default='Конструктор чехлов', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Конструктор чехлов',
                'verbose_name_plural': 'Конструктор чехлов',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('hex', models.CharField(help_text='Пример: #a4a4a4', max_length=7, verbose_name='Цвет')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default='0', verbose_name='Цена')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Seam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.PositiveSmallIntegerField(default='0', verbose_name='Цена')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Отстрочка',
                'verbose_name_plural': 'Отстрочка',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SeamColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('hex', models.CharField(help_text='Пример: #a4a4a4', max_length=7, verbose_name='Цвет')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Seam', verbose_name='Отстрочка')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет отстрочки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.CaseBuilder')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='seam',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='color',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='base',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Type'),
        ),
    ]
