# Generated by Django 2.1.1 on 2019-08-03 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_rear'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='mate-builder', editable=False, unique=True)),
                ('title', models.CharField(default='Конструктор ковриков', editable=False, max_length=255)),
                ('nameplate', models.PositiveSmallIntegerField(default=10, verbose_name='Максимальное количество шильдиков')),
                ('nameplate_image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение шильдика')),
                ('bearing', models.ImageField(blank=True, upload_to='', verbose_name='Изображение подпятника')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Базовая цена')),
                ('nameplate_price', models.PositiveIntegerField(default=0, verbose_name='Цена за 1 шильдик')),
                ('bearing_price', models.PositiveIntegerField(default=0, verbose_name='Цена за подпятник')),
                ('set', models.TextField(blank=True, help_text='Каждый сет с новой строки', verbose_name='Наборы')),
            ],
            options={
                'verbose_name': 'Конструктор ковриков',
                'verbose_name_plural': 'Конструктор ковриков',
            },
        ),
        migrations.CreateModel(
            name='MateColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.MateBuilder', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Цвет коврика',
                'verbose_name_plural': 'Цвета коврика',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MateSeamColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('hex', models.CharField(help_text='Пример: #a4a4a4', max_length=7, verbose_name='Цвет')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.MateBuilder', verbose_name='Отстрочка')),
            ],
            options={
                'verbose_name': 'Цвет канта',
                'verbose_name_plural': 'Цвета канта',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='base',
            options={'ordering': ['order'], 'verbose_name': 'Основа', 'verbose_name_plural': 'Основы (чехлы)'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['order'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы (чехлы)'},
        ),
        migrations.AlterModelOptions(
            name='rear',
            options={'ordering': ['order'], 'verbose_name': 'Тыл', 'verbose_name_plural': 'Тылы (чехлы)'},
        ),
        migrations.AlterModelOptions(
            name='seam',
            options={'ordering': ['order'], 'verbose_name': 'Отстрочка', 'verbose_name_plural': 'Отстрочка (чехлы)'},
        ),
    ]
