# Generated by Django 2.1.1 on 2020-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20200204_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebuilder',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=260, verbose_name='Мета описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casebuilder',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Ключевые слова'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casebuilder',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='СЕО Заголовок'),
            preserve_default=False,
        ),
    ]
