# Generated by Django 2.1.1 on 2018-11-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainreview',
            old_name='test1',
            new_name='test',
        ),
    ]
