# Generated by Django 2.1.1 on 2019-02-20 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20190218_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
