# Generated by Django 2.1.1 on 2018-10-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='html',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='blank',
            field=models.BooleanField(default=False, verbose_name='В новой вкладке'),
        ),
    ]
