# Generated by Django 2.1.1 on 2019-04-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20181102_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order']},
        ),
    ]
