# Generated by Django 2.1.1 on 2019-04-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20190418_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
    ]
