# Generated by Django 2.1.1 on 2019-07-30 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yandex_money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Если установить значение "0", то доставка отобразится как бесплатная, <br>Если поле оставить пустым, то заказчик увидит подпись "Уточняйте у менеджера"', null=True, verbose_name='Стоимость доставки')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.UUID('5077dcbd-2eea-49b2-9127-a18c2a37640f'), max_length=256, verbose_name='UUID')),
                ('current_status', models.PositiveSmallIntegerField(choices=[(1, 'Заказ принят'), (5, 'Подтвержден'), (6, 'Самовывоз'), (7, 'Установка'), (8, 'Доставка'), (9, 'Отправка ТК'), (10, 'Отправка почтой'), (11, 'Доступен для оплаты онлайн'), (12, 'Оплачен'), (2, 'Выполнен'), (4, 'Не дозвонились'), (3, 'Отменен')], default=1, verbose_name='текущий статус')),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'Оплата недоступна'), (2, 'Доступна оплата'), (3, 'Ожидается получение оплаты'), (4, 'Оплачен')], default=1, verbose_name='Статус оплаты')),
                ('amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Общее кол-во предметов')),
                ('pay_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Способ оплаты')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма покупки')),
                ('products_json', models.TextField(blank=True, null=True, verbose_name='JSON Информация о товарах')),
                ('products_info', models.TextField(verbose_name='Информация о товарах')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID пользователя')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('yandex_payment_req', models.CharField(blank=True, max_length=255, null=True, verbose_name='yandex payment req id')),
                ('yandex_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='yandex payment id')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_method', to='order.DeliveryMethod', verbose_name='Способ доставки')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_money.Payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=256, verbose_name='Ключ сессии')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID товара')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за штуку')),
                ('install', models.BooleanField(default=False, verbose_name='Установка')),
                ('install_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за установку')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес товара (кг)')),
                ('size', models.CharField(blank=True, max_length=128, null=True, verbose_name='Размер')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
