# Generated by Django 2.1.1 on 2019-10-05 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190803_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a8a65b32-a517-4f39-aeed-ad6366126a17'), max_length=256, verbose_name='UUID'),
        ),
    ]
