# Generated by Django 2.1.1 on 2019-10-15 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191005_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('78e57683-20af-4fb3-94d7-d1b7eacbac07'), max_length=256, verbose_name='UUID'),
        ),
    ]
