# Generated by Django 2.1.1 on 2019-10-15 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191015_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8f74caad-0551-4170-970b-2474202d0427'), max_length=256, verbose_name='UUID'),
        ),
    ]
