# Generated by Django 2.1.1 on 2019-12-11 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191211_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('989e4a6b-007b-4b6a-bc91-34fdc93d1d85'), max_length=256, verbose_name='UUID'),
        ),
    ]
