# Generated by Django 2.1.1 on 2020-02-04 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191211_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4b2314e8-85a2-4376-8398-3d91fd60b31c'), max_length=256, verbose_name='UUID'),
        ),
    ]
