# Generated by Django 2.1.1 on 2020-02-04 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200204_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('998115eb-38b2-4502-bf69-d57f606dfbad'), max_length=256, verbose_name='UUID'),
        ),
    ]
