# Generated by Django 2.1.1 on 2020-02-04 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200204_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b24ef4e7-adf8-4ab9-a5ed-e9642b5fceeb'), max_length=256, verbose_name='UUID'),
        ),
    ]
