# Generated by Django 2.1.1 on 2020-02-04 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200204_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a18b927b-86cc-4b58-8f63-7433e77d464b'), max_length=256, verbose_name='UUID'),
        ),
    ]
