# Generated by Django 2.1.1 on 2020-02-04 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200204_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('fe754d54-b934-4afb-8fad-a2feb169b2a0'), max_length=256, verbose_name='UUID'),
        ),
    ]
