# Generated by Django 2.1.1 on 2020-02-04 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200204_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('15ed8e08-a9f0-4231-86f7-68b2cc3b560e'), max_length=256, verbose_name='UUID'),
        ),
    ]
