# Generated by Django 2.1.1 on 2020-02-06 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20200205_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('601d432d-1192-414f-a7bb-072895e54b1c'), max_length=256, verbose_name='UUID'),
        ),
    ]
