# Generated by Django 2.1.1 on 2020-03-06 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200206_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1c9be023-04c3-4c23-b092-70270acaa037'), max_length=256, verbose_name='UUID'),
        ),
    ]
