# Generated by Django 2.1.1 on 2020-03-06 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20200306_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4a073c2e-9dba-4517-a595-7d8362f5a6ef'), max_length=256, verbose_name='UUID'),
        ),
    ]
