# Generated by Django 2.1.1 on 2020-03-10 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200306_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5c93c3c5-ef09-4966-8ad3-e7e41fa52f2e'), max_length=256, verbose_name='UUID'),
        ),
    ]
