# Generated by Django 2.1.1 on 2020-06-08 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200310_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('01abca7a-a24d-4e94-b458-257877a52fca'), max_length=256, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
