# Generated by Django 2.1.1 on 2020-06-17 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200617_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4fdbb5c9-32f4-41cd-8cb8-4121a559e16f'), max_length=256, verbose_name='UUID'),
        ),
    ]
