# Generated by Django 2.1.1 on 2020-07-20 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200617_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2c8d9469-d160-49c5-82c2-9207e57bb40c'), max_length=256, verbose_name='UUID'),
        ),
    ]
