# Generated by Django 2.1.1 on 2020-07-20 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20200720_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c0104056-4342-4909-97b8-20dcb6e8b700'), max_length=256, verbose_name='UUID'),
        ),
    ]
