# Generated by Django 2.1.1 on 2020-07-28 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20200720_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('77a5a563-affd-409b-adba-4e11c13ef5f1'), max_length=256, verbose_name='UUID'),
        ),
    ]
