# Generated by Django 2.1.1 on 2020-07-28 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20200728_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.UUID('39f5830a-8f6a-45ea-b92d-1d00590481c6'), max_length=256, verbose_name='UUID'),
        ),
    ]
